name: Sync to SignSing Repository

on:
  push:
    branches: ["main"]

jobs:
  sync:
    if: github.repository == 'signal-singularity/lucky-docs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name "SignSing Bot"
          git config --global user.email "admin@sings.ee"
      
      - name: Push to SignSing repository
        run: |
          git remote add target https://x-access-token:${{ secrets.SSBOT_PAT }}@github.com/SignSing/lucky-docs.git
          git push target main:main --force
