name: Sync to SignSing Repository

on:
  push:
    branches: ["main"]

jobs:
  sync:
    if: github.repository == 'signal-singularity/lucky-docs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to SignSing repository
        run: |
          git remote remove origin
          git remote add origin https://SignSing:${{ secrets.SSBOT_PAT }}@github.com/SignSing/lucky-docs.git
          git push origin main:main --force
